name: BloodMoon
version: '1.4'
main: bluenightfury46.dev.bloodMoon.BloodMoon
api-version: '1.21'
authors: [ BlueNightFury46 ]
description: Adds Blood moons to the game
website: bluenightfury46.dev
commands:
  setequipement:
    description: 'Sets the equipement that entities get during Blood-Moons'

  trigger:
    description: 'Forces a Blood-Moon to be triggered'
  reload-bloodmoon:
    description: 'Reloads the plugin'
    aliases:
      - bloodmoon-reload
      - reload

permissions:
  bloodmoon.setequipement:
    description: 'Allows you to use the /setequipement command'
  bloodmoon.trigger:
    description: 'Allows you to use the /trigger command'
  bloodmoon.reload:
    description: 'Allows you to use the /reload-bloodmoon command'




